### ISSUE TITLE
advice from me 😁

### ISSUE THREAD

**Issue by NulTx** [jkrei0/onu-online#1]
## `(⌒▽⌒;)`

_edit :_
_or how to change the card to png i need it to make a telegram bot_

**Comment by jkrei0** [comment]
I'm not quite sure what you mean.
Are you trying to change the image on the card (if so, the whole card or just the little icons)?
Or do you want to copy these cards as pngs to use elsewhere?

**Comment by NulTx** [comment]
> I'm not quite sure what you mean. Are you trying to change the image on the card (if so, the whole card or just the little icons)? Or do you want to copy these cards as pngs to use elsewhere?

Like this [uno-online](https://uno-game.now.sh/) & [source code](https://github.com/Grispi/Uno_Game)

**Comment by jkrei0** [comment]
Ah. There are probably multiple good ways to do it. The easiest one that comes to mind would be:

For face-up cards
- In the `public` folder, make a new folder "`images`" (or anything, really) & put the pngs in it
- edit the `cardSymbol` function (`game.js:164`) to return the image source instead 
- if you name your pngs something easy like "`blue7.png`" you could do something like:
```js
return '/images/' + card.color + card.number + '.png';
```
- change the html to add the images. Anywhere you see `{{ cardSymbol( ... ) }}` , do
```html
<img :src="cardSymbol( ... )">
```
- Next to the `{{ cardSymbol( ... ) }` there will be some `svg` elements for wild, reverse, etc icons. You probably want to delete those.

Then for the face-down cards
- replace the svg for other players' cards (`index.html:73`) with something like `<img src="/images/faceDownCard.png">`. Also add an img on line 121 for the draw pile.
- *(If you plan on playing with +2/+4 stacking turned on, you'll have to add a separate way of telling how many cards are stacked .. or just play without a counter)*

After this, it'll probably look quite odd, so you'll have to edit the css. It'll probably be a good bit of work to do that, I'm not sure what you might have to change.

**Comment by NulTx** [comment]
## I understand, thank you
